### ISSUE TITLE
Exposure notificatie: zoveel mogelijk informatie ontvangen

### ISSUE THREAD

**Issue by maxvisser** [minvws/nl-covid19-notification-app-design#11]
Ten eerste: Tof dat dit open is!

Ik was benieuwd of we al weten wat zoveel 'mogelijk informatie' is. Welke informatie biedt de api van google/apple. Wat kun je allemaal laten zien over de ontmoeting?

**Comment by jamalv** [comment]
👋 

De specificaties van de API zijn hier te vinden: https://www.apple.com/covid19/contacttracing

Ik heb het zelf niet allemaal doorgelezen maar voor zover ik begrijp wordt er voor je telefoon een UID aangemaakt. Als iemand met jou in aanraking komt wordt de UID van jouw telefoon gelogd. Als jij vervolgens een diagnose krijgt wordt jouw UID geflagged en krijgen alle mensen die met je in contact zijn geweest een notificatie. De hoeveelheid informatie is dus volgens mij enorm beperkt en niet te herleiden tot een natuurlijk persoon. Maar nogmaals, ik heb niet alles gelezen dus ken alleen de strekking :)

**Comment by maxvisser** [comment]
Het mooiste is om die data dan te kunnen verreiken. Belangrijkste lijkt me tijdstip en datum. Maar ik zie me ook voor me dat je naar buiten gaat en dat je locatiegevens/GPS aan kunt zetten in de app of een klein logboek kan bijhouden

**Comment by jamalv** [comment]
On device bedoel je? Als in; als gebruiker wil ik weten waar, wanner en hoe laat ik in contact ben geweest ben met iemand die Covid heeft? Ik denk dat dit niet haalbaar is in het kader van privacy. Het lijkt me dat de keuze om deze dataset zo beperkt te houden heel bewust is gemaakt.

**Comment by maxvisser** [comment]
Zie datum en tijd wel als must have. Dan kun je zelf iig je agenda er bij pakken of Google maps timeline gebruiken om te kijken waar je was.

**Comment by jamalv** [comment]
Hmmm 🤔 is dat zo? Gaat het er niet vooral om _dat_ je onlangs in contact bent geweest met _iemand_ die besmet is? Zodat je weet dat je zelf nu dus ook risico loopt en op je hoede moet zijn? Het lijkt me dat je die verdere informatie niet per-se nodig hebt. Waarom denk je dat het belangrijk is?

**Comment by bwbroersma** [comment]
This repo is about the visual design only. This is not the correct repo for this issue: this is RTFM stuff :slightly_smiling_face:
API documentation can be found at [Apple](https://www.apple.com/covid19/contacttracing/) and [Google](https://www.google.com/covid19/exposurenotifications/).

Sadly, there only is a 'Slack' channel to discuss stuff at https://praatmee.codefor.nl/ channels #notificatie-app and #corona-apps

**Comment by jamalv** [comment]
Ah yea, thx, I made a pr to update TFM: https://github.com/minvws/nl-covid19-notification-app-design/pull/13 😉

**Comment by maxvisser** [comment]
Well I looked at figma and did not see any screens yet about this story. @bwbroersma as the story is not really descriptive probably making a screen will be pretty hard if you don't know what to visualize. :) so slack is the right place for this?

**Comment by bwbroersma** [comment]
@maxvisser 
> Maar ik zie me ook voor me dat je naar buiten gaat en dat je locatiegevens/GPS aan kunt zetten in de app of een klein logboek kan bijhouden

The current working process is a bit failed, lacking static images on Github (see #18 for a partial solution). The discussion on Slack is also very chaotic, I proposed [Discourse](https://www.discourse.org/) many times, to have a public orderly discussion, but to no avail yet.

About your GPS comment:
- Using location data is banned by Apple/Google, this is [long known news](https://www.imore.com/apple-and-google-ban-location-tracking-contact-tracing-apps). See also the [Exposure Notification - Frequently Asked Questions by Apple](https://covid19-static.cdn-apple.com/applications/covid19/current/static/contact-tracing/pdf/ExposureNotification-FAQv1.1.pdf):
> **10.How will apps get approval to use this system?**
> Apps will receive approval based on a specific set of criteria designed to ensure they are only administered in conjunction with public health authorities, meet our privacy requirements, and protect user data.
>
> The criteria are detailed separately in agreements that developers enter into to use the API, and are organized around the principles of functionality and user privacy. *There will be restrictions on the data that apps can collect when using the API, **including not being able to request access to location services***, and restrictions on how data can be used.

- Looking at the design you can see GPS is out of the question:
![image](https://user-images.githubusercontent.com/4252918/83133178-bf414400-a0e2-11ea-9c60-22bdded3c523.png)

**Comment by maxvisser** [comment]
Do you know if time/date is available though; as in does the phone store when he got in contact or only if he got in contact with a specific UID?

**Comment by bwbroersma** [comment]
There are no UIDs (User IDs), there are DTKs (Daily Tracing Keys), and even those are not send over Bluetooth (but are published and downloaded if infected). But before going into all details, please read the [documentation by Apple](https://www.apple.com/covid19/contacttracing/), from the top to the bottom and the start till the end :slightly_smiling_face:

A orderly and open public discussion would be great, any platform, it does not has to be FOSS in this case.

**Comment by maxvisser** [comment]
Thanks for your time and clear response :) I understand its pretty difficult project. 
I will close this issue. Better to move this discussion somewhere else.

P.s. Really profile picture, cool that you are in delft. See that you are person many [words](https://www.broersma.com/) 😄😄.
