### ISSUE TITLE
Suggestie user story

### ISSUE THREAD

**Issue by henkkelder** [minvws/nl-covid19-notification-app-design#12]
Als gebruiker wil ik bij 'first time use' kunnen kiezen om alle uitleg over te slaan en gewoon de app te activeren.

Reden: Voor veel mensen is de detailuitleg al te gecompliceerd. Alhoewel veel mensen digivaardig zijn, zijn er ook nog veel mensen dat helemaal niet. (Dit zeg ik obv 40 jaar ervaring met software ontwikkeling en het verlenen van support voor software en apps.)
Om ook voor die laatste categorie de app toegankelijk te maken zou ik een shortcut mogelijk willen maken.
Op youtube/sociale media/tv kunnen altijd uitleg fimpjes getoond worden.

**Comment by jelleprins** [comment]
Ja, in onze eerdere designs zie je deze terug komen.

Uiteindelijk (voor dit ontwerp) hebben we ervoor gekozen omdat we zagen dat veel mensen de onboarding dan oversloegen, en vervolgens niet goed begrepen wat de app doet. Ze sloegen de onboarding over als automatisme.

**Comment by dannylagrouw** [comment]
Een filmpje met uitleg in de app is misschien sowieso een goed idee.

**Comment by jorisleker** [comment]
@dannylagrouw Mits er een toegankelijk alternatief is. En de app een relatief kleine downloadable blijft :-) Filmpje nemen we sowieso mee voor publiekscampagne en ondersteunende website.

**Comment by jorisleker** [comment]
@henkkelder closing for now, but will add this story as a research topic to our usability testing with less digital savvy audiences. Ok with you?

**Comment by henkkelder** [comment]
That would be fine. Keep in mind there are more “laaggeletterden”  then one would suspect. Most of them are also not very “digi-vaardig”. 

 

Personally I believe the biggest challenge lies there, to get people to install the app.

 

I’ve been a front-end developer with a big insurer for a short period. There a e-learning course “Vertrouwd communiceren” was mandatory. They strongly believed you loose users where things are too complicated. Now I work for an Arbodienst and I see the same problems where official language often works as a blockade. 

 

Succes en groeten

Henk Kelder

**Comment by jorisleker** [comment]
Thanks for bringing this up @henkkelder. We have test specially aimed at people with low literacy lined up for the upcoming weeks. Will be extra aware about this /cc @jobjansweijer
