### ISSUE TITLE
Taalfouten

### ISSUE THREAD

**Issue by ph00lt0** [minvws/nl-covid19-notification-app-design#21]
"Bij GGD geweest" moet zijn "Bij de GGD geweest"

"Je krijgt een bericht als je een besmettingsrisico hebt gelopen" ?

"De app ziet via Bluetooth of je dicht bij iemand bent geweest" moet zijn in de richting van "De app ziet met het gebuik van Bluetooth of je dicht in de buurt van een persoon bent geweest."

**Comment by danoszz** [comment]
@ph00lt0 eens met de eerste suggestie. 

Echter in de context van een UI, is de derde zin sterker als het korter is. Als de essentie het zelfde is, dan zijn [beknopte zinnen positiever](https://www.nngroup.com/articles/how-users-read-on-the-web/) voor de UX.

**Comment by ph00lt0** [comment]
De tweede zin klopt volgens mij grammaticaal niet. Volgens mij moet het of zijn: 
"Je krijgt een bericht als je 'besmettingsrisico' hebt gelopen" of 
"Je krijgt een bericht als je een besmettingsrisico hebt op gelopen" of 
"Je krijgt een bericht als je een risico hebt gelopen op besmetting"

De derde zin zou kan uiteraard korter maar moet wel kloppen. Een suggestie:
"Met het gebruik van Bluetooth kan de app zien bij wie je in de buurt bent geweest"

**Comment by RobenScholten** [comment]
Corona test = coronatest bij 'vraag corona test aan' op hoofdscherm

**Comment by ryanbnl** [comment]
@ph00lt0 tip: repo forken, fixes maken in je fork, dan een PR maken :)

**Comment by ph00lt0** [comment]
@ryanbnl tip: de fouten staan in het prototype, in Figma. :)

**Comment by ryanbnl** [comment]
D'oh :)

**Comment by tvangeijn** [comment]
@ph00lt0
Wat dacht je van: "Je krijgt een melding nadat je extra kans op besmetting hebt gelopen" ?

**Comment by ph00lt0** [comment]
@tvangeijn ja veel beter!

**Comment by jorisleker** [comment]
@tvangeijn lijkt erop dat dit issue is opgepakt in design. Ik sluit me. Feel free to reopen if needed.
