### ISSUE TITLE
User Story: huidige status laten zien

### ISSUE THREAD

**Issue by joostbijl** [minvws/nl-covid19-notification-app-design#23]
Een van de meest gebruikte stories lijkt me dat je jouw status kunt laten zien aan iemand anders. Ik vind dit nu niet terug als een expliciete story vanuit de requirements of in de 'job stories'. 

categorie: daily use
motivatie: wil mijn besmettingsstatus aan derden laten zien op een eenduidige manier
verwacht resultaat: zodat iemand anders kan vaststellen of ik besmet ben of niet. (en op basis daarvan bijvoorbeeld toegang tot een winkel kan bepalen)

**Comment by jorisleker** [comment]
Ik herken de behoefte, maar het is niet de bedoeling dat de app dit gaat ondersteunen. Gebruik van de app voor andere doelen dan ondersteuning van contactonderzoek wordt vanuit de overheid waarschijnlijk zelfs expliciet verboden. 

Daarnaast rijmt het niet met het uitgangspunt dat gebruik van de app vrijwillig is. Als gebruikers van de app specifieke privileges krijgen in het dagelijks verkeer, dan gaat daar een zekere druk van uit om de app ook te installeren. Niet helemaal de bedoeling.
