### ISSUE TITLE
Impliciete auteursrecht overdracht

### ISSUE THREAD

**Issue by jeroenleenarts** [minvws/nl-covid19-notification-app-design#5]
In de read me van dit project staat onderaan de mededeling dat bijdragers er mee instemmen dat alle auteursrechten overgedragen worden aan de staat.

Sla art. 156a BRv er op na. Auteursrecht overdracht vereist uitdrukkelijke instemming. Ook Uitdrukkelijke instemming vereist dat je duidelijk vraagt of ze instemmen met de gestelde voorwaarde.

Auteursrecht overdracht impliceert overigens geen persoonsrecht overdracht.

Bijdragers kunnen op dit moment ten alle tijden hun rechten afdwingen. Lijkt mij niet helemaal handig.

Ook is het verstandiger in een Nederlands stuk de Nederlandse terminologie te hanteren.

**Comment by ThijmenDeValk** [comment]
Om een pull request te kunnen doen, moet je expliciet instemmen met de [CLA](https://cla-assistant.io/minvws/nl-covid19-notification-app-design). Daarin staat onder meer:

> The Contributor hereby grants the Ministry a perpetual, worldwide, non-exclusive, sublicensable, irrevocable and unrestricted right of use to the Contributions. This right of use pertains to all intellectual property rights that could attach to the Contributions, which in any event includes copyrights, trademark rights, database rights and patents.

Daarmee wordt auteursrecht inderdaad niet overgedragen, maar de niet-exclusieve licentie lost het probleem ook op, toch?
