### ISSUE TITLE
Contribute

### ISSUE THREAD

**Issue by pierrekil** [minvws/nl-covid19-notification-app-design#8]
We definitely like to contribute if using our open source console app adds value. Licensing is ok, but English language would help...

**Comment by bwbroersma** [comment]
>  if using our open source console app adds value

Which app?

**Comment by jorisleker** [comment]
@pierrekil can you be a bit more specific on how you could contribute? Closing this issue for now to keep things tidy. Please feel free to reopen with some more explanation.
