### ISSUE TITLE
Very minor text alignment issue 

### ISSUE THREAD

**Issue by martijntraa** [minvws/nl-covid19-notification-app-design#87]
While on iOS 13.5 using iPhone X with language set to `English (UK)`, 
using app version `Test and research version 1.0.2 (68559-89543ff)`,
I noticed a very slight text alignment issue in the intro slides.

### To Reproduce
Couldn't find a way to trigger the intro again, so from the beginning:

1. Install the app, open the app.
2. Go through the introduction slides.
3. As far as I remember, alignment of text to icons looks equal everywhere, fitting about two lines of text next to icons on the left. On the "Turn on notifications about possible coronavirus exposure" slide.

### Observed
The text is misaligned to the icons.

### Expected
Expected text to be aligned higher ;-)

### Screenshots / observed
![IMG_6070](https://user-images.githubusercontent.com/4265101/90366190-588b5100-e067-11ea-9b9e-4892582e1bb3.jpg)

Great job on the app everyone, looks great/friendly/trustworthy/everything.

**Comment by jorisleker** [comment]
This has been fixed quite a while ago. Closing this :-)
