### ISSUE TITLE
[DATE]: [VWS/Covid19NotificationApp]

### ISSUE THREAD

**Issue by herkocoomans** [minvws/nl-covid19-notification-app-design#88]
### Textual issues in accessibility statement (NL)

1. Go to 'Over de app'
2. Scroll down to 'Toegankelijkheid'
3. Scroll down to 'Hoe we zorgen voor een toegankelijke CoronaMelder?'

The title of this section is gramatically incorrect. I suggest 'Hoe zorgen we voor een toegankelijke CoronaMelder app?'

Second bullitpoint: 'In het ontwerp van de app is rekening gehouden met toegankelijkheid. Zo is waar een tekstalternatief voor afbeeldingen gebruikt en is er gelet op het gebruik van kleur en kleurcontrast' is gramatically incorrect. 
I suggest 'In het ontwerp van de app is rekening gehouden met toegankelijkheid. Zo is overal een tekstalternatief voor afbeeldingen beschikbaar en is er gelet op het correcte gebruik van kleur en kleurcontrast'

Fourth bullitpoint" 'De toegankelijkhied van de app is zowel door het team als een onafhankelijke partij getest'. I suggest adding a link to the test results of the independant third party.

 - OS: iOS 13.6
 - App version: Test- en onderzoeksversie 1.0.2 (68559-89543ff)
 
### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md
 
##Update: edited title of this issue for clarity

**Comment by jorisleker** [comment]
The accessibility statement is hosted at coronamelder.nl and not inside the app. @herkocoomans I've created an issue in the coronamelder.nl repository, and will close this one here.
