### ISSUE TITLE
User stories: Inzicht in notificaties op postcode niveau 

### ISSUE THREAD

**Issue by TeunVR** [minvws/nl-covid19-notification-app-design#9]
In de User Stories staat 1 could-have story:
“wil ik inzicht in het aantal notificaties op postcode niveau”.

Dat suggereert kennis van lokatie (Gps etc), ik denk dat dit onwenselijk is.

Het is ook tegenstrijdig met de productdefinitie waar (terecht) staat:
“De app maakt geen gebruik van locatiegegevens en slaat deze ook niet op. Niet met GPS, niet op een andere manier.“

**Comment by sanderploegsma** [comment]
Het zou ook zonder locatiegegevens moeten kunnen, bijvoorbeeld wanneer gebruikers bij het instellen van de app eenmalig hun postcode invullen.

**Comment by TeunVR** [comment]
Dat is waar. Alleen is de vraag of dit dan “metadata” van de client is.

https://covid19-static.cdn-apple.com/applications/covid19/current/static/contact-tracing/pdf/ExposureNotification-CryptographySpecificationv1.2.pdf#page10

The server must not retain metadata from clients uploading Diagnosis Keys after including those key in the aggregated list of Diagnosis Keys per day.

**Comment by bwbroersma** [comment]
> postcode

PC6 (volledige postcode) of PC4 (alleen de 4 cijfers)?

**Comment by jorisleker** [comment]
We gaan deze story aanpassen, want een beetje verwarrend in z'n huidige vorm. De story vind z'n oorsprong in de behoefte van mensen om meer te weten over de risico's die ze in het dagelijks leven lopen: "waart het virus in mijn omgeving vrij rond" én de behoefte te weten of de app effectief is/werkt.  

Die _behoeftes_ bestaan, het is de vraag of we ze gaan beantwoorden _in_ de app (anders dan door blootstellingsnotificiaties als je bij een positief getest persoon in de buurt bent geweest). De vertaling naar een feature in de app is hier iets te snel/letterlijk gemaakt. Thanks for spotting.
