### ISSUE TITLE
Request: focus on reliability on power saving smartphones

### ISSUE THREAD

**Issue by jjt00** [minvws/nl-covid19-notification-app-design#90]
(Dutch below)
Many smartphones have a nasty habit of restricting or disabling background apps ("power saving"). I see this as a major risk for the CoronaMelder, since it has to send signals at any time to be effective. The app does not pay any attention to this, while not every smartphone user knows how to make an exception for an app to be able to run in the background.
There is the possibility to implement a screen in the app in which people are referred to the correct screen with settings, so that with 1 click the energy saving can be turned off for CoronaMelder. This would be a welcome addition.
**Edit:** I closed this issue because I was pointed to GEAN. However, this is in addition to GEAN, which works well mainly on stock Android. Other android versions (MIUI, OxygenOS) have built-in functions that can undermine the app. Therefore, add a detection of the operating system, so that where necessary a screen can be automatically shown in which energy saving can be switched off. See the screenshot below of MIUI 11 (android 10) where "autostart" and 3 "other permissions" now have to be set manually. Even when the app itself works with battery optimization enabled, push notifications might not show up to warn people.

Veel smartphones hebben de nare gewoonte dat ze apps op de achtergrond beperken of uitschakelen ("energiebesparing"). Ik zie dit als een groot risico voor de CoronaMelder, aangezien deze eigenlijk altijd een signaal moet versturen om effectief te kunnen zijn. In de app wordt hier géén aandacht aan besteed, terwijl lang niet elke smartphonegebruiker weet hoe ze een uitzondering kunnen maken voor een app om wél op de achtergrond te kunnen draaien.
Er is de mogelijkheid om een scherm in de app te implementeren waarin men naar het juiste scherm met instellingen wordt verwezen, zodat met 1 klik de energiebesparing uitgezet kan worden voor CoronaMelder. Dit zou een welkome toevoeging zijn.
**Toevoeging:** Ik heb dit issue gesloten omdat ik werd gewezen op GEAN. Dit is echter een aanvulling op GEAN, welke voornamelijk op stock Android goed werkt. Op andere android versies (MIUI, OxygenOS) zitten functies ingebouwd die de app kunnen ondermijnen. Voeg daarom een detectie van het besturingssysteem toe, zodat waar nodig automatisch een scherm getoond kan worden waarin men energiebesparing uit kan zetten. Zie onderstaand screenshot van MIUI 11 (android 10) waarbij "autostart" en 3 "andere toestemmingen" nu handmatig ingesteld moeten worden.
Zelfs wanneer de app werkt met energiebesparing aan, kan het zijn dat meldingen niet weergegeven worden en iemand zo niet tijdig gewaarschuwd wordt.

**Comment by jjt00** [comment]
![Screenshot_2020-08-17-15-21-39-035_com miui securitycenter](https://user-images.githubusercontent.com/59733689/90401605-7922cd80-e09e-11ea-9816-3c4dfb5e36ef.jpg)
Screenshot van MIUI 11 waarbij de gebruiker zelf meerdere ingrepen moet doen, om werking op de achtergrond te kunnen garanderen

**Comment by jorisleker** [comment]
@jjt00 As this concerns the android version of the app, and the issue needs to be investigated before we create a design for it, could you please also create an issue in https://github.com/minvws/nl-covid19-notification-app-android and reference this on there?

**Comment by hvisser** [comment]
This is already being tracked for Android here: https://github.com/minvws/nl-covid19-notification-app-android/issues/23

**Comment by jorisleker** [comment]
Ok, closing it here because it's a duplicate
