### ISSUE TITLE
Feature Request: indicate the (approximate) number of detected devices in current proximity

### ISSUE THREAD

**Issue by damianh** [minvws/nl-covid19-notification-app-design#94]
### Describe the bug, issue or concern

The success of this application highly depends on it's adoption. Since it is not mandatory, for me to feel confident I need to be able to determine it's effectiveness at any given moment at my current location. For example, if I am with a group of people and the app tells it has not detected any (or few) nearby devices then I can make the informed choice to leave that location (and I will personally judge such people to be inconsiderate 😉). 

As this might have an affect on battery life, it would not be something that should be run constantly but instead on demand for a period of time. i.e. "Monitor for next "x" minutes". 

(Note: I have no idea if the underlying iOS/Android SDKs support this).

**Comment by raymens** [comment]
I like the sound of it regarding convincing and or determining if it's a relative "safe" area.

However I guess it will also expose a big privacy and security issue. I can imagine a burglar waiting for the scan next to a house. But this might already be an issue regardless due to Bluetooth and other signals.

**Comment by damianh** [comment]
Regarding privacy there is no personally identifiable information. Indeed, detecting proximity devices by (low power) bluetooth is by design. One of the features of this app is that you need to be in proximity for 15 minutes to be considered "contact" (so someone cycling past you won't count). Therefore the app is tracking not just which devices are in proximity but for how long too. The necessary data to implement this is already captured on your phone. In this feature I am seeking an (approximate) counter and nothing more. I can visually compare the counter to the number of people around me.

Regarding security, such applications and devices already exist e.g. [BlueSniff](https://apps.apple.com/us/app/blue-sniff-simple-bluetooth-detector/id1205673451) and [BlueFinder](https://play.google.com/store/apps/details?id=com.bluetoothFinder&hl=en) as well as others based on WiFi, electromagnetic radiation detection, IR, etc.

**Comment by jorisleker** [comment]
The underlying iOS/Android API does not support this. The app does not have direct access to bluetooth nor the realtime results of proximity scanning. All information is stored in the secure enclave of your OS. Google and Apple don't allow apps implementing the Exposure Notification framework to ask additional permissions that would enable them to access bluetooth. 

Other apps _could_ support this feature, and proofs of concepts have already been build (i.e this in-browser tool https://janmisker.github.io/GAEN-Scanner/). Note however, that it might be hard to get apps that implement this into the AppStores. They probably breach Apple / Google's terms of service. Feel free to try though :-)

**Comment by damianh** [comment]
@jorisleker Understood and thanks for the detailed reasoning. This feature would need to be directed upstream.
