### ISSUE TITLE
22aug20: Enhancement at tab 'Coronatest aanvragen' --> CoronaTest.nl

### ISSUE THREAD

**Issue by bobromeo** [minvws/nl-covid19-notification-app-design#95]
### Describe the bug, issue or concern

The page in the app 'Coronatest aanvragen' should also lead people to the site CoronaTest.nl

**Smartphone:**
 - Device: Huawei Mate 10 Pro
 - OS: Android 10
 - Browser: Chrome
 - Version: 84

**Comment by cafferata** [comment]
This has already been realized in the latest version.

**Comment by bobromeo** [comment]
Thx!
