### ISSUE TITLE
App crash in FAQ

### ISSUE THREAD

**Issue by jscheeres** [minvws/nl-covid19-notification-app-design#98]
### Describe the bug, issue or concern

App crashes in the FAQ.

### To Reproduce
1. Go to Questions about this app
2. Click in “What does a notification say”
3. App crash

### Expected behavior

Show answer on FAQ question.

**Smartphone:**
 -  Device: iPhone 11
 - OS: iOS 14.2

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by roelspruit** [comment]
Jikes. Thanks a lot for bringing this to our attention. We are planning a release in the coming days and I'll make sure that a fix for this is included. Internal ticket created with number 59321.

**Comment by jorisleker** [comment]
This has been fixed a while ago, thanks again @jscheeres
